Handle "Server '' not found in known_hosts exception
The message with "reject_unknown_hosts" and "abort_on_prompts" is rather
missleading as paramiko returns:

    SSHException: Server 'localhost' not found in known_hosts

but fabric reports:

    Needed to prompt for a connection or sudo password (host:
    localhost), but abort-on-prompts was set to True

This patch handles the special case similarly to existing workarounds.

Signed-off-by: Lukáš Doktor <ldoktor@redhat.com>