Fix a show_commands() function's issue:
Consider the task function's comment of a fabfile.py contains non ASCII char, just like this:
```
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from fabric.api import task, run

@task
def test():
    """
    测试1234
    """
    run('env')
```

It need be execute through a parallel.py script which uses subprocess.Popen:
```
import subprocess

logfile = 'fabric.log'
logf = open(logfile, 'a')
args = ['fab', '-Hroot@192.168.100.18', 'test2']
p = subprocess.Popen(args, stdout=logf, stderr=logf)
p.wait()
```

The new process will throw a exception, fabric.log is written like this:
```

Warning: Command(s) not found:
    test2

Traceback (most recent call last):
  File "c:\python27\lib\site-packages\fabric\main.py", line 729, in main
    show_commands(None, options.list_format, 1)
  File "c:\python27\lib\site-packages\fabric\main.py", line 592, in show_commands
    print("\n".join(list_commands(docstring, format)))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 31-32: ordinal not in range(128)
```

Because the comment in fabfile.py is unicode, while redirect to logf, it should encode to string using python's default encoding (ascii), and then failed.

To solve this issue, I modified the show_commands() function in fabric/main.py, add some code to change the output unicode to bytes explicitly.

Best wishes.